#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertfaculty(faculty instance);
    partial void Updatefaculty(faculty instance);
    partial void Deletefaculty(faculty instance);
    partial void Insertdept(dept instance);
    partial void Updatedept(dept instance);
    partial void Deletedept(dept instance);
    partial void InsertBBA_course_list(BBA_course_list instance);
    partial void UpdateBBA_course_list(BBA_course_list instance);
    partial void DeleteBBA_course_list(BBA_course_list instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    #endregion
		
		public dbDataContext() : 
				base(global::WindowsFormsApplication2.Properties.Settings.Default.dbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<faculty> faculties
		{
			get
			{
				return this.GetTable<faculty>();
			}
		}
		
		public System.Data.Linq.Table<dept> depts
		{
			get
			{
				return this.GetTable<dept>();
			}
		}
		
		public System.Data.Linq.Table<CSE_course_list> CSE_course_lists
		{
			get
			{
				return this.GetTable<CSE_course_list>();
			}
		}
		
		public System.Data.Linq.Table<BBA_course_list> BBA_course_lists
		{
			get
			{
				return this.GetTable<BBA_course_list>();
			}
		}
		
		public System.Data.Linq.Table<student> students
		{
			get
			{
				return this.GetTable<student>();
			}
		}
		
		public System.Data.Linq.Table<EEE_course_list> EEE_course_lists
		{
			get
			{
				return this.GetTable<EEE_course_list>();
			}
		}
		
		public System.Data.Linq.Table<taken_course> taken_courses
		{
			get
			{
				return this.GetTable<taken_course>();
			}
		}
		
		public System.Data.Linq.Table<fprereg> fpreregs
		{
			get
			{
				return this.GetTable<fprereg>();
			}
		}
		
		public System.Data.Linq.Table<sprereg> spreregs
		{
			get
			{
				return this.GetTable<sprereg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _admin_Id;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_IdChanging(string value);
    partial void Onadmin_IdChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string admin_Id
		{
			get
			{
				return this._admin_Id;
			}
			set
			{
				if ((this._admin_Id != value))
				{
					this.Onadmin_IdChanging(value);
					this.SendPropertyChanging();
					this._admin_Id = value;
					this.SendPropertyChanged("admin_Id");
					this.Onadmin_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.faculty")]
	public partial class faculty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _faculty_Id;
		
		private string _password;
		
		private string _name;
		
		private string _gender;
		
		private string _dept;
		
		private System.Nullable<System.DateTime> _birth_date;
		
		private System.Nullable<long> _phone;
		
		private string _address;
		
		private string _country;
		
		private string _city;
		
		private string _nationality;
		
		private string _email;
		
		private EntityRef<dept> _dept1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfaculty_IdChanging(string value);
    partial void Onfaculty_IdChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OndeptChanging(string value);
    partial void OndeptChanged();
    partial void Onbirth_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dateChanged();
    partial void OnphoneChanging(System.Nullable<long> value);
    partial void OnphoneChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnnationalityChanging(string value);
    partial void OnnationalityChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public faculty()
		{
			this._dept1 = default(EntityRef<dept>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faculty_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string faculty_Id
		{
			get
			{
				return this._faculty_Id;
			}
			set
			{
				if ((this._faculty_Id != value))
				{
					this.Onfaculty_IdChanging(value);
					this.SendPropertyChanging();
					this._faculty_Id = value;
					this.SendPropertyChanged("faculty_Id");
					this.Onfaculty_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept", DbType="VarChar(50)")]
		public string dept
		{
			get
			{
				return this._dept;
			}
			set
			{
				if ((this._dept != value))
				{
					if (this._dept1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndeptChanging(value);
					this.SendPropertyChanging();
					this._dept = value;
					this.SendPropertyChanged("dept");
					this.OndeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_date", DbType="Date")]
		public System.Nullable<System.DateTime> birth_date
		{
			get
			{
				return this._birth_date;
			}
			set
			{
				if ((this._birth_date != value))
				{
					this.Onbirth_dateChanging(value);
					this.SendPropertyChanging();
					this._birth_date = value;
					this.SendPropertyChanged("birth_date");
					this.Onbirth_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="BigInt")]
		public System.Nullable<long> phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(50)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="VarChar(50)")]
		public string nationality
		{
			get
			{
				return this._nationality;
			}
			set
			{
				if ((this._nationality != value))
				{
					this.OnnationalityChanging(value);
					this.SendPropertyChanging();
					this._nationality = value;
					this.SendPropertyChanged("nationality");
					this.OnnationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dept_faculty", Storage="_dept1", ThisKey="dept", OtherKey="dept1", IsForeignKey=true)]
		public dept dept1
		{
			get
			{
				return this._dept1.Entity;
			}
			set
			{
				dept previousValue = this._dept1.Entity;
				if (((previousValue != value) 
							|| (this._dept1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dept1.Entity = null;
						previousValue.faculties.Remove(this);
					}
					this._dept1.Entity = value;
					if ((value != null))
					{
						value.faculties.Add(this);
						this._dept = value.dept1;
					}
					else
					{
						this._dept = default(string);
					}
					this.SendPropertyChanged("dept1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dept")]
	public partial class dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dept1;
		
		private EntitySet<faculty> _faculties;
		
		private EntitySet<student> _students;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondept1Changing(string value);
    partial void Ondept1Changed();
    #endregion
		
		public dept()
		{
			this._faculties = new EntitySet<faculty>(new Action<faculty>(this.attach_faculties), new Action<faculty>(this.detach_faculties));
			this._students = new EntitySet<student>(new Action<student>(this.attach_students), new Action<student>(this.detach_students));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dept", Storage="_dept1", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string dept1
		{
			get
			{
				return this._dept1;
			}
			set
			{
				if ((this._dept1 != value))
				{
					this.Ondept1Changing(value);
					this.SendPropertyChanging();
					this._dept1 = value;
					this.SendPropertyChanged("dept1");
					this.Ondept1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dept_faculty", Storage="_faculties", ThisKey="dept1", OtherKey="dept")]
		public EntitySet<faculty> faculties
		{
			get
			{
				return this._faculties;
			}
			set
			{
				this._faculties.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dept_student", Storage="_students", ThisKey="dept1", OtherKey="dept")]
		public EntitySet<student> students
		{
			get
			{
				return this._students;
			}
			set
			{
				this._students.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_faculties(faculty entity)
		{
			this.SendPropertyChanging();
			entity.dept1 = this;
		}
		
		private void detach_faculties(faculty entity)
		{
			this.SendPropertyChanging();
			entity.dept1 = null;
		}
		
		private void attach_students(student entity)
		{
			this.SendPropertyChanging();
			entity.dept1 = this;
		}
		
		private void detach_students(student entity)
		{
			this.SendPropertyChanging();
			entity.dept1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CSE_course_list")]
	public partial class CSE_course_list
	{
		
		private string _course_id;
		
		private string _course_name;
		
		private System.Nullable<int> _creadit_hour;
		
		private string _Prerequisite_;
		
		public CSE_course_list()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this._course_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="VarChar(50)")]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this._course_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creadit_hour", DbType="Int")]
		public System.Nullable<int> creadit_hour
		{
			get
			{
				return this._creadit_hour;
			}
			set
			{
				if ((this._creadit_hour != value))
				{
					this._creadit_hour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prerequisite ]", Storage="_Prerequisite_", DbType="VarChar(50)")]
		public string Prerequisite_
		{
			get
			{
				return this._Prerequisite_;
			}
			set
			{
				if ((this._Prerequisite_ != value))
				{
					this._Prerequisite_ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BBA_course_list")]
	public partial class BBA_course_list : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _course_id;
		
		private string _course_name;
		
		private System.Nullable<int> _creadit_hour;
		
		private string _Prerequisite_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncourse_idChanging(string value);
    partial void Oncourse_idChanged();
    partial void Oncourse_nameChanging(string value);
    partial void Oncourse_nameChanged();
    partial void Oncreadit_hourChanging(System.Nullable<int> value);
    partial void Oncreadit_hourChanged();
    partial void OnPrerequisite_Changing(string value);
    partial void OnPrerequisite_Changed();
    #endregion
		
		public BBA_course_list()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this.Oncourse_idChanging(value);
					this.SendPropertyChanging();
					this._course_id = value;
					this.SendPropertyChanged("course_id");
					this.Oncourse_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="VarChar(50)")]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this.Oncourse_nameChanging(value);
					this.SendPropertyChanging();
					this._course_name = value;
					this.SendPropertyChanged("course_name");
					this.Oncourse_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creadit_hour", DbType="Int")]
		public System.Nullable<int> creadit_hour
		{
			get
			{
				return this._creadit_hour;
			}
			set
			{
				if ((this._creadit_hour != value))
				{
					this.Oncreadit_hourChanging(value);
					this.SendPropertyChanging();
					this._creadit_hour = value;
					this.SendPropertyChanged("creadit_hour");
					this.Oncreadit_hourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prerequisite ]", Storage="_Prerequisite_", DbType="VarChar(50)")]
		public string Prerequisite_
		{
			get
			{
				return this._Prerequisite_;
			}
			set
			{
				if ((this._Prerequisite_ != value))
				{
					this.OnPrerequisite_Changing(value);
					this.SendPropertyChanging();
					this._Prerequisite_ = value;
					this.SendPropertyChanged("Prerequisite_");
					this.OnPrerequisite_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _student_id;
		
		private string _password;
		
		private string _student_name;
		
		private string _father_name;
		
		private string _gender;
		
		private string _date_of_birth;
		
		private string _phoneno;
		
		private string _address;
		
		private string _country;
		
		private string _city;
		
		private string _nationality;
		
		private string _Email;
		
		private string _dept;
		
		private string _start_semister;
		
		private EntityRef<dept> _dept1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstudent_idChanging(string value);
    partial void Onstudent_idChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onstudent_nameChanging(string value);
    partial void Onstudent_nameChanged();
    partial void Onfather_nameChanging(string value);
    partial void Onfather_nameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void Ondate_of_birthChanging(string value);
    partial void Ondate_of_birthChanged();
    partial void OnphonenoChanging(string value);
    partial void OnphonenoChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnnationalityChanging(string value);
    partial void OnnationalityChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OndeptChanging(string value);
    partial void OndeptChanged();
    partial void Onstart_semisterChanging(string value);
    partial void Onstart_semisterChanged();
    #endregion
		
		public student()
		{
			this._dept1 = default(EntityRef<dept>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string student_id
		{
			get
			{
				return this._student_id;
			}
			set
			{
				if ((this._student_id != value))
				{
					this.Onstudent_idChanging(value);
					this.SendPropertyChanging();
					this._student_id = value;
					this.SendPropertyChanged("student_id");
					this.Onstudent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_name", DbType="VarChar(50)")]
		public string student_name
		{
			get
			{
				return this._student_name;
			}
			set
			{
				if ((this._student_name != value))
				{
					this.Onstudent_nameChanging(value);
					this.SendPropertyChanging();
					this._student_name = value;
					this.SendPropertyChanged("student_name");
					this.Onstudent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_father_name", DbType="VarChar(50)")]
		public string father_name
		{
			get
			{
				return this._father_name;
			}
			set
			{
				if ((this._father_name != value))
				{
					this.Onfather_nameChanging(value);
					this.SendPropertyChanging();
					this._father_name = value;
					this.SendPropertyChanged("father_name");
					this.Onfather_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="VarChar(50)")]
		public string date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phoneno", DbType="VarChar(50)")]
		public string phoneno
		{
			get
			{
				return this._phoneno;
			}
			set
			{
				if ((this._phoneno != value))
				{
					this.OnphonenoChanging(value);
					this.SendPropertyChanging();
					this._phoneno = value;
					this.SendPropertyChanged("phoneno");
					this.OnphonenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(50)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nationality", DbType="VarChar(50)")]
		public string nationality
		{
			get
			{
				return this._nationality;
			}
			set
			{
				if ((this._nationality != value))
				{
					this.OnnationalityChanging(value);
					this.SendPropertyChanging();
					this._nationality = value;
					this.SendPropertyChanged("nationality");
					this.OnnationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dept", DbType="VarChar(50)")]
		public string dept
		{
			get
			{
				return this._dept;
			}
			set
			{
				if ((this._dept != value))
				{
					if (this._dept1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndeptChanging(value);
					this.SendPropertyChanging();
					this._dept = value;
					this.SendPropertyChanged("dept");
					this.OndeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_semister", DbType="VarChar(50)")]
		public string start_semister
		{
			get
			{
				return this._start_semister;
			}
			set
			{
				if ((this._start_semister != value))
				{
					this.Onstart_semisterChanging(value);
					this.SendPropertyChanging();
					this._start_semister = value;
					this.SendPropertyChanged("start_semister");
					this.Onstart_semisterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dept_student", Storage="_dept1", ThisKey="dept", OtherKey="dept1", IsForeignKey=true)]
		public dept dept1
		{
			get
			{
				return this._dept1.Entity;
			}
			set
			{
				dept previousValue = this._dept1.Entity;
				if (((previousValue != value) 
							|| (this._dept1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dept1.Entity = null;
						previousValue.students.Remove(this);
					}
					this._dept1.Entity = value;
					if ((value != null))
					{
						value.students.Add(this);
						this._dept = value.dept1;
					}
					else
					{
						this._dept = default(string);
					}
					this.SendPropertyChanged("dept1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EEE_course_list")]
	public partial class EEE_course_list
	{
		
		private string _course_id;
		
		private string _course_name;
		
		private System.Nullable<int> _creadit_hour;
		
		private string _Prerequisite_;
		
		public EEE_course_list()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this._course_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="VarChar(50)")]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this._course_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creadit_hour", DbType="Int")]
		public System.Nullable<int> creadit_hour
		{
			get
			{
				return this._creadit_hour;
			}
			set
			{
				if ((this._creadit_hour != value))
				{
					this._creadit_hour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Prerequisite ]", Storage="_Prerequisite_", DbType="VarChar(50)")]
		public string Prerequisite_
		{
			get
			{
				return this._Prerequisite_;
			}
			set
			{
				if ((this._Prerequisite_ != value))
				{
					this._Prerequisite_ = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taken_course")]
	public partial class taken_course
	{
		
		private string _sId;
		
		private string _sname;
		
		private string _course_id;
		
		private string _course_name;
		
		private string _fid;
		
		private string _fname;
		
		private System.Nullable<double> _mid_marke;
		
		private string _mid_grade;
		
		private string _final_mark;
		
		private string _final_grade;
		
		private string _creadit;
		
		private string _prereq;
		
		private string _semister;
		
		private string _Sdept;
		
		private string _Fdept;
		
		private System.Nullable<int> _day1;
		
		private System.Nullable<int> _day2;
		
		private System.Nullable<int> _day3;
		
		private System.Nullable<int> _day4;
		
		private System.Nullable<int> _day5;
		
		public taken_course()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sId
		{
			get
			{
				return this._sId;
			}
			set
			{
				if ((this._sId != value))
				{
					this._sId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sname", DbType="VarChar(50)")]
		public string sname
		{
			get
			{
				return this._sname;
			}
			set
			{
				if ((this._sname != value))
				{
					this._sname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_id", DbType="VarChar(50)")]
		public string course_id
		{
			get
			{
				return this._course_id;
			}
			set
			{
				if ((this._course_id != value))
				{
					this._course_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_name", DbType="VarChar(50)")]
		public string course_name
		{
			get
			{
				return this._course_name;
			}
			set
			{
				if ((this._course_name != value))
				{
					this._course_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fid", DbType="VarChar(50)")]
		public string fid
		{
			get
			{
				return this._fid;
			}
			set
			{
				if ((this._fid != value))
				{
					this._fid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this._fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[mid-marke]", Storage="_mid_marke", DbType="Float")]
		public System.Nullable<double> mid_marke
		{
			get
			{
				return this._mid_marke;
			}
			set
			{
				if ((this._mid_marke != value))
				{
					this._mid_marke = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid_grade", DbType="VarChar(50)")]
		public string mid_grade
		{
			get
			{
				return this._mid_grade;
			}
			set
			{
				if ((this._mid_grade != value))
				{
					this._mid_grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_mark", DbType="VarChar(50)")]
		public string final_mark
		{
			get
			{
				return this._final_mark;
			}
			set
			{
				if ((this._final_mark != value))
				{
					this._final_mark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_grade", DbType="VarChar(50)")]
		public string final_grade
		{
			get
			{
				return this._final_grade;
			}
			set
			{
				if ((this._final_grade != value))
				{
					this._final_grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creadit", DbType="VarChar(50)")]
		public string creadit
		{
			get
			{
				return this._creadit;
			}
			set
			{
				if ((this._creadit != value))
				{
					this._creadit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prereq", DbType="VarChar(50)")]
		public string prereq
		{
			get
			{
				return this._prereq;
			}
			set
			{
				if ((this._prereq != value))
				{
					this._prereq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semister", DbType="VarChar(50)")]
		public string semister
		{
			get
			{
				return this._semister;
			}
			set
			{
				if ((this._semister != value))
				{
					this._semister = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdept", DbType="VarChar(50)")]
		public string Sdept
		{
			get
			{
				return this._Sdept;
			}
			set
			{
				if ((this._Sdept != value))
				{
					this._Sdept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fdept", DbType="VarChar(50)")]
		public string Fdept
		{
			get
			{
				return this._Fdept;
			}
			set
			{
				if ((this._Fdept != value))
				{
					this._Fdept = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day1", DbType="Int")]
		public System.Nullable<int> day1
		{
			get
			{
				return this._day1;
			}
			set
			{
				if ((this._day1 != value))
				{
					this._day1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day2", DbType="Int")]
		public System.Nullable<int> day2
		{
			get
			{
				return this._day2;
			}
			set
			{
				if ((this._day2 != value))
				{
					this._day2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day3", DbType="Int")]
		public System.Nullable<int> day3
		{
			get
			{
				return this._day3;
			}
			set
			{
				if ((this._day3 != value))
				{
					this._day3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day4", DbType="Int")]
		public System.Nullable<int> day4
		{
			get
			{
				return this._day4;
			}
			set
			{
				if ((this._day4 != value))
				{
					this._day4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day5", DbType="Int")]
		public System.Nullable<int> day5
		{
			get
			{
				return this._day5;
			}
			set
			{
				if ((this._day5 != value))
				{
					this._day5 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fprereg")]
	public partial class fprereg
	{
		
		private int _status;
		
		private string _semister;
		
		public fprereg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semister", DbType="VarChar(50)")]
		public string semister
		{
			get
			{
				return this._semister;
			}
			set
			{
				if ((this._semister != value))
				{
					this._semister = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sprereg")]
	public partial class sprereg
	{
		
		private int _status;
		
		private string _semister;
		
		public sprereg()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semister", DbType="VarChar(50)")]
		public string semister
		{
			get
			{
				return this._semister;
			}
			set
			{
				if ((this._semister != value))
				{
					this._semister = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
