<?xml version="1.0" encoding="utf-8"?><Database Name="db" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\db.mdf;Integrated Security=True" SettingsObjectName="WindowsFormsApplication2.Properties.Settings" SettingsPropertyName="dbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="admin_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.faculty" Member="faculties">
    <Type Name="faculty">
      <Column Name="faculty_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dept" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="birth_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nationality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="dept_faculty" Member="dept1" ThisKey="dept" OtherKey="dept1" Type="dept" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dept" Member="depts">
    <Type Name="dept">
      <Column Name="dept" Member="dept1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="dept_faculty" Member="faculties" ThisKey="dept1" OtherKey="dept" Type="faculty" />
      <Association Name="dept_student" Member="students" ThisKey="dept1" OtherKey="dept" Type="student" />
    </Type>
  </Table>
  <Table Name="dbo.CSE_course_list" Member="CSE_course_lists">
    <Type Name="CSE_course_list">
      <Column Name="course_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="course_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="creadit_hour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Prerequisite ]" Member="Prerequisite_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BBA_course_list" Member="BBA_course_lists">
    <Type Name="BBA_course_list">
      <Column Name="course_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="course_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="creadit_hour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Prerequisite ]" Member="Prerequisite_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.student" Member="students">
    <Type Name="student">
      <Column Name="student_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="student_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="father_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phoneno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nationality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dept" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="start_semister" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="dept_student" Member="dept1" ThisKey="dept" OtherKey="dept1" Type="dept" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EEE_course_list" Member="EEE_course_lists">
    <Type Name="EEE_course_list">
      <Column Name="course_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="course_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="creadit_hour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Prerequisite ]" Member="Prerequisite_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.taken_course" Member="taken_courses">
    <Type Name="taken_course">
      <Column Name="sId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="course_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="course_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[mid-marke]" Member="mid_marke" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="mid_grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="final_mark" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="final_grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="creadit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prereq" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="semister" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sdept" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fdept" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="day1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="day2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="day3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="day4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="day5" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.fprereg" Member="fpreregs">
    <Type Name="fprereg">
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="semister" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sprereg" Member="spreregs">
    <Type Name="sprereg">
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="semister" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>